Adding method for delayed publishing
chillr/sevak pull request #1
Opened 2018-02-08 06:11 UTC by kmaheshwari

2018-02-08 11:22 UTC, deepakkumarnd requested changes

2018-02-08 11:22 UTC, deepakkumarnd commented on lib/sevak/publisher.rb
> +    def self.delayed_publish(queue_name, message, delay = 0)
Please add a documentation on the usage in the README.md and is the delay is in seconds ?

2018-02-08 11:57 UTC, kmaheshwari commented on lib/sevak/publisher.rb
> +    def self.delayed_publish(queue_name, message, delay = 0)
the delay is in milliseconds

2018-02-09 05:16 UTC, deepakkumarnd approved these changes

2018-02-09 05:16 UTC, merged